package com.smarttask.smarttask_backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UuidGenerator;
import java.time.Instant;
import java.util.UUID;

/**
 * WHY:
 * Stores refresh tokens for JWT authentication (token rotation & revocation).
 * Linked to User, one user can have multiple valid refresh tokens.
 */
@Entity
@Table(name = "refresh_tokens")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RefreshToken {

    /** Primary key (UUID auto-generated by Hibernate) */
    @Id
    @UuidGenerator
    @Column(nullable = false, updatable = false)
    private UUID id;

    /** Many tokens belong to one user (foreign key) */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id")
    private User user;

    /** The actual token string stored in DB */
    @Column(nullable = false, length = 500)
    private String token;

    /** Expiration time */
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    /** Soft revoke flag (for logout/all tokens invalidation) */
    @Column(nullable = false)
    private boolean revoked;

    /** Created timestamp */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** Automatically set created_at and default revoked = false before insert */
    @PrePersist
    void prePersist() {
        createdAt = Instant.now();
        revoked = false;
    }
}
